#spring:
#  application:
#    name: springboot3-shardingsphere-demo
#  datasource:
#    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
#    # 指定 YAML 配置文件 sharding-jdbc.yaml
#    url: jdbc:shardingsphere:classpath:sharding-jdbc.yaml

# application.yml
spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-jdbc.yaml
