version: "3.2"

# 定义服务，可以多个
services:
  redis-cluster:
    container_name: redis-cluster
    image: redis:latest
    command: redis-cli -a 123456 --cluster create  14.103.123.142:6380 14.103.123.142:6381 14.103.123.142:6382 --cluster-replicas 0  --cluster-yes
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
  redis-node1: # 服务名称
    image: redis:latest # 创建容器时所需的镜像
    container_name: redis-node1 # 容器名称
    restart: always # 容器总是重新启动
    ports:
      - 6380:6380
      - 16380:16380
    volumes: # 数据卷，目录挂载
      - ./etc_rc.local:/etc/rc.local
      - ./node1/redis.conf:/etc/redis/redis.conf
      - ./node1/data:/data
    command: redis-server /etc/redis/redis.conf # 覆盖容器启动后默认执行的命令

  redis-node2:
    image: redis:latest
    container_name: redis-node2
    restart: always
    ports:
      - 6381:6381
      - 16381:16381
    volumes:
      - ./etc_rc.local:/etc/rc.local
      - ./node2/redis.conf:/etc/redis/redis.conf
      - ./node2/data:/data
    command: redis-server /etc/redis/redis.conf

  redis-node3:
    image: redis:latest
    container_name: redis-node3
    restart: always
    ports:
      - 6382:6382
      - 16382:16382
    volumes:
      - ./etc_rc.local:/etc/rc.local
      - ./node3/redis.conf:/etc/redis/redis.conf
      - ./node3/data:/data
    command: redis-server /etc/redis/redis.conf