
version: '3.6'

# 网桥 -> 方便相互通讯
networks:
  mysql:
    driver: bridge

services:
  mysql-master:
    image: mysql:5.7
    container_name: mysql_master                                  # 容器名为'mysql_master'
    restart: unless-stopped                                       # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    volumes:                                                      # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./master/my.cnf:/etc/mysql/my.cnf"
      - "./master/data:/var/lib/mysql"
      - "./master/log/error.log:/var/log/error.log"
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: 123456         # 设置root用户密码
    ports:                              # 映射端口
      - "3307:3306"
    networks:
      - mysql

  mysql-slave1:
    image: mysql:5.7
    container_name: mysql_slave1                                   # 容器名为'mysql_slave'
    restart: unless-stopped                                       # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    volumes:                                                      # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./slave1/my.cnf:/etc/mysql/my.cnf"
      - "./slave1/data:/var/lib/mysql"
      - "./slave1/log/error.log:/var/log/error.log"
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: 123456         # 设置root用户密码
    ports:                              # 映射端口
      - "3308:3306"
    depends_on:
      - mysql-master
    networks:
      - mysql

  mysql-slave2:
    image: mysql:5.7
    container_name: mysql_slave2                                   # 容器名为'mysql_slave'
    restart: unless-stopped                                       # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    volumes:                                                      # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./slave2/my.cnf:/etc/mysql/my.cnf"
      - "./slave2/data:/var/lib/mysql"
      - "./slave2/log/error.log:/var/log/error.log"
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: 123456         # 设置root用户密码
    ports:                              # 映射端口
      - "3309:3306"
    depends_on:
      - mysql-master
    networks:
      - mysql